### PR TITLE
Update the dtsi core device tree file of EZPRO Mrkaio M68S and EZPRO Mrkaio M68S PLUS models.

### PR DESCRIPTION
**Pull request by xiaomeng9597**

### CODE REVIEW

**Comment by jjm2473** [comment]
npu有啥问题吗？

**Comment by xiaomeng9597** [comment]
> npu有啥问题吗？

应该正常的吧，下面的rknpu部分内核日志

[   10.570770] RKNPU fde40000.npu: Adding to iommu group 0
[   10.571661] RKNPU fde40000.npu: RKNPU: rknpu iommu is enabled, using iommu mode
[   10.571748] RKNPU fde40000.npu: Looking up rknpu-supply from device tree
[   10.572375] RKNPU fde40000.npu: Looking up mem-supply from device tree
[   10.572522] RKNPU fde40000.npu: can't request region for resource [mem 0xfde40000-0xfde4ffff]
[   10.573114] [drm] Initialized rknpu 0.8.5 20230202 for fde40000.npu on minor 1
[   10.573421] RKNPU fde40000.npu: Looking up rknpu-supply from device tree
[   10.573473] vdd_npu: could not add device link fde40000.npu: -EEXIST
[   10.573497] RKNPU fde40000.npu: Looking up mem-supply from device tree
[   10.573511] vdd_npu: could not add device link fde40000.npu: -EEXIST
[   10.573685] RKNPU fde40000.npu: leakage=4
[   10.573737] RKNPU fde40000.npu: pvtm = 87610, from nvmem
[   10.573755] RKNPU fde40000.npu: pvtm-volt-sel=2
[   10.573784] RKNPU fde40000.npu: opp_parse_supplies: Invalid number of elements in opp-microvolt property (3) with supplies (2)
[   10.573793] RKNPU fde40000.npu: _of_add_opp_table_v2: Failed to add OPP, -22
[   10.573800] RKNPU fde40000.npu: Invalid operating-points in device tree.
[   10.573806] RKNPU fde40000.npu: RKNPU: failed to init_opp_table

**Comment by xiaomeng9597** [comment]
这是小马软路由m68s的日志图片，我看了电犀牛r68s的也是这样，应该是正常的吧，不过HDMI那个节点必须把DTS_NO_LEGACY 的判断去掉，否则编译后的固件设备树文件HDMI节点会没有。 
Screenshot_2024-12-30-12-56-29-128_bin mt plus

**Comment by jjm2473** [comment]
那没必要禁用npu节点啊

**Comment by xiaomeng9597** [comment]
> 那没必要禁用npu节点啊

嗯，合并一下吧

**Pull request merged**
